cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

chineseSpicyApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment', include('payment.urls', namespace='payment')),
    path('', include('chineseSpicyFlavor.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chineseSpicyFlavor/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, re_path

from . import views

app_name = 'chineseSpicyFlavor'

urlpatterns = [

    re_path(r'^customerView/$', views.customerView, name='customerView'),
    path('', views.covidWarning, name='covidWarning'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('myOrders/', views.order_list, name='myOrders'),
    path('myOrders/<int:pk>/details', views.order_detail, name='OrderDetail'),
    path('myOrders/<int:pk>/delete', views.order_delete, name='OrderDelete'),
    # path('signup/', views.signup, name='signup'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='user_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done.html'),
    path('password_reset/confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm.html'),
    path('foods/', views.product_list, name='product_list'),
    path('foods/<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
    path('foods/<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
    path('edit/', views.edit, name='edit'),
    path('address/', views.display_addresses, name="displayAddresses"),
    path('address/<int:pk>/edit/', views.address_edit, name='address_edit'),
    path('address/create/', views.address_new, name='address_new'),
    path('address/<int:pk>/delete', views.address_delete, name='address_delete'),
    path('orders/', views.ViewAllOrders.as_view(), name='ViewAllOrders'),
    path('orders/<int:pk>/details', views.AdminOrderDetail, name='AdminOrderDetail'),
    path('orders/<int:pk>/delete', views.AdminOrderDelete, name='AdminOrderDelete'),
    path('sales/', views.Sales.as_view(), name='Sales'),
    path('customers/', views.Customers.as_view(), name='Customers')

]

chineseSpicyFlavor/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Address


class EditAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('streetNum', 'zipcode', 'state', 'city')


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image',)

class SignUp(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='')
    last_name = forms.CharField(max_length=30, required=True, help_text='Optional.')
    phoneNumber = forms.CharField(max_length=10, help_text='', required=True,
                                  widget=forms.TextInput(attrs={'placeholder': 'Phone Number'}))
    street_number = forms.CharField(max_length=20, help_text='', required=True,
                                    widget=forms.TextInput(attrs={'placeholder': 'Street Number'}))
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


from django.contrib.auth.models import User


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    first_name = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    # email = forms.CharField(label='', widget=forms.EmailInput(attrs={'placeholder', 'johndoe@example.com'}))
    email = forms.CharField(label='', max_length=100,
                            widget=forms.EmailInput
                            (attrs={'placeholder': 'Enter your email'}))
    password = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}), required=True)
    password2 = forms.CharField(label='',
                                widget=forms.PasswordInput(attrs={'placeholder': 'Verify Password'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('streetNum', 'zipcode', 'city', 'state')

chineseSpicyFlavor/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from .models import Product, Category, Profile, Address
from orders.models import Order, OrderItem
from django.shortcuts import render, get_object_or_404
from cart.forms import CartAddProductForm
from .forms import AddressForm, UserEditForm, ProfileEditForm
from django.http import HttpResponse
from cart.views import cart_detail
from django.http import HttpResponse, HttpResponseRedirect
import datetime
from django.contrib import messages
import random
from django.db.models import Sum
from _decimal import Decimal


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()

    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


# Create your views here.
def home(request):
    # Render the html template home.html with the data in the context variable
    return render(request, 'home.html')


def covidWarning(request):
    if request.user.is_authenticated:
        return customerView(request)
    else:
        return render(request, 'covidPrec.html')


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'home.html')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})


from django.contrib.auth.decorators import login_required


@login_required
def customerView(request):
    orders = Order.objects.filter(profile_id=request.user.id)

    orderItem = OrderItem.objects.filter(order__profile_id=request.user.id)
    mostLiked = OrderItem.objects.filter(order__profile_id=request.user.id, quantity__gt=10, )

    mostLiked = list(set(mostLiked))
    items = list(Product.objects.all())
    random.shuffle(items)
    random_items = items[:4]
    mostLiked = mostLiked[:3]
    return render(request, 'account/base.html',
                  {'orders': orders, 'n': range(3), 'orderItem': orderItem,
                   'random_items': random_items, 'mostLiked': mostLiked})


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user,
                                 data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile,
            data=request.POST,
            files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Profile Updated Successfully')
            return customerView(request)
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(
            instance=request.user.profile)
    return render(request,
                  'account/edit.html',
                  {'user_form': user_form,
                   'profile_form': profile_form})


from .forms import LoginForm, UserRegistrationForm


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(
                user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request,
                          'registration/register_done.html',
                          {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'registration/register.html',
                  {'user_form': user_form})


# Create a prototype view that displays the user's addresses on file
@login_required
def display_addresses(request):
    addresses = Address.objects.filter(user_id=request.user)
    return render(request, 'account/addresses.html', {'addresses': addresses})


@login_required
def address_new(request):
    if request.method == "POST":
        form = AddressForm(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.save()
            addresses = Address.objects.filter(user_id=request.user)
            form.save()
            messages.success(request, 'Address Added Successfully')
            return HttpResponseRedirect('/')
    else:
        form = AddressForm()
    return render(request, 'account/address_new.html', {'form': form})


@login_required
def address_edit(request, pk):
    address = get_object_or_404(Address, pk=pk)
    if request.method == "POST":
        form = AddressForm(request.POST, instance=address)
        if form.is_valid():
            address = form.save()
            # service.customer = service.id
            address.save()
            addresses = Address.objects.filter(user_id=request.user)
            return render(request, 'account/addresses.html', {'addresses': addresses})
    else:
        # print("else")
        form = AddressForm(instance=address)
    return render(request, 'account/address_edit.html', {'form': form})


@login_required()
def address_delete(request, pk):
    address = get_object_or_404(Address, pk=pk)
    address.delete()
    return redirect('chineseSpicyFlavor:displayAddresses')


@login_required
def order_list(request):
    orders = Order.objects.filter(profile_id=request.user.id)
    return render(request, 'account/order_list.html', {'orders': orders})


@login_required
def order_delete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.delete()
    messages.success(request, 'Order Deleted Succesfully')
    return HttpResponseRedirect('/')


@login_required
def order_detail(request, pk):
    order_instance = get_object_or_404(Order, pk=pk)
    orderItems = OrderItem.objects.filter(order=order_instance)

    return render(request, 'account/order_detail.html', {'order_instance': order_instance, 'orderItems': orderItems})


def about(request):
    return render(request, 'about.html')


@login_required
def user_logout(request):
    try:
        for key in list(request.session.keys()):
            if key == 'CART':
                continue

            del request.session[key]
    except KeyError:
        pass
    return HttpResponseRedirect(reversed('your_app:login'))


from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views import generic


class ViewAllOrders(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view to see all of the orders"""
    model = Order
    permission_required = 'orders.order.can_view_order'
    template_name = 'manager/AllOrders.html'
    paginate_by = 10

    def get_queryset(self):
        return Order.objects.all().order_by('profile__user', 'id')


@login_required
def AdminOrderDetail(request, pk):
    order_instance = get_object_or_404(Order, pk=pk)
    orderItems = OrderItem.objects.filter(order=order_instance)

    return render(request, 'account/order_detail.html', {'order_instance': order_instance, 'orderItems': orderItems})


@login_required
def AdminOrderDelete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.delete()
    messages.success(request, 'Order Deleted Succesfully')
    return HttpResponseRedirect('/')


class Sales(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view to see all of the orders"""
    model = Order
    labels = []
    data = []
    permission_required = 'orders.order.can_view_order'
    template_name = 'manager/Sales.html'

    queryset = Order.objects.filter(created__day=datetime.date.today().day, created__month=datetime.date.today().month,
                                    created__year=datetime.date.today().year).order_by('profile', 'id')
    for order in queryset:
        labels.append(order.delivery_pref)
        data.append(order.get_total_cost().real.real)

    for d in data:
        totalSales = sum(data)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(Sales, self).get_context_data(**kwargs)
        context.update({'totalSales' : self.totalSales})
        return context

class Customers(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view to view all customers and relevant information"""
    model = Profile
    permission_required = 'chineseSpicyFlavor.profile.can_add_profile'
    template_name = 'manager/Customers.html'

    def get_queryset(self):
        return Profile.objects.all()

chineseSpicyFlavor/templates/manager/AllOrders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order</title>
    <link rel="stylesheet" href="../../static/css/management.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

</head>
<body>
<div class="top">
    <div style="text-align: center;">
        <ul>
            <li><a href="{% url 'chineseSpicyFlavor:covidWarning' %}">Home Page</a></li>
            <li><a href="#">ACCOUNT</a>
                <ul>

                    <li><a href="{% url 'chineseSpicyFlavor:edit' %}">Edit Account</a></li>

                </ul>
            </li>

            <li><a href="#">ADDRESSES</a>
                <ul>

                    <li><a href="{% url 'chineseSpicyFlavor:address_new' %}">Add an address</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:displayAddresses' %}">My Addresses</a></li>

                </ul>
            </li>

            <li><a href="#">MENU</a>
                <ul>
                    <li><a href="{% url 'chineseSpicyFlavor:product_list' %}">Foods</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:product_list' %}">Order Now</a></li>
                </ul>
            </li>

            <li><a href="#">ORDER</a>
                <ul>
                    <li><a href="{% url 'chineseSpicyFlavor:product_list' %}">Order Now</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:myOrders' %}">My Orders</a></li>

                </ul>
            </li>
            {% if user.is_staff %}
                <li><a href="#">ADMIN</a>
                    <ul>
                        <li><a href="{% url 'chineseSpicyFlavor:ViewAllOrders' %}">Orders</a></li>
                        <li><a href="{% url 'chineseSpicyFlavor:Sales' %}">Sales</a></li>
                        <li><a href="{% url 'chineseSpicyFlavor:Customers' %}">Customers</a></li>
                    </ul>
                </li>
            {% endif %}

            <ul>
                <li><a href="{% url 'chineseSpicyFlavor:logout' %}">Logout</a></li>
            </ul>
        </ul>
    </div>
</div>
<h1>Orders</h1>
<table class="styled-table">
    <thead>
    <tr>
        <th>Customer</th>
        <th>Order ID</th>
        <th>Order Date</th>
        <th>Order Delivery</th>
        <th>Total Cost</th>
        <th colspan="3">Actions</th>

    </tr>
    </thead>

    {% for order in order_list %}
        <tbody>
        <tr>
            <td>{{ order.profile.user }}</td>
            <td>{{ order.id }}</td>
            <td>{{ order.created}}</td>
            {% ifnotequal order.address.pk None %}
                <td>{{ order.address.streetNum }}<br>{{ order.address.city }},{{ order.address.state }}<br>{{ order.address.zipcode }}
                </td>

            {% endifnotequal %}
            {% ifequal order.address.pk None %}
                <td>Chinese Spicy Flavor</td>
            {% endifequal %}
            <td>${{ order.get_total_cost }}</td>
            <td><a href="{% url 'chineseSpicyFlavor:AdminOrderDetail' pk=order.pk %}"
                   class="btn btn-primary">Reciept</a>
                {% if order.paid %}
                    <a href="{% url 'chineseSpicyFlavor:ViewAllOrders' %}" class="btn btn-primary"
                       style="background-color:green;">Paid</a>
                {% else %}
                    <a href="{% url 'chineseSpicyFlavor:ViewAllOrders' %}" class="btn btn-primary"
                       style="background-color: red">Not Paid</a>

                {% endif %}

                <a href="{% url 'chineseSpicyFlavor:AdminOrderDelete' pk=order.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            </td>

        </tr>
        </tbody>


    {% endfor %}
</table>
</body>
</html>

chineseSpicyFlavor/templates/manager/Customers.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Customers</title>
    <link rel="stylesheet" href="../../static/css/management.css">
</head>
<body>
<div class="top">
    <div style="text-align: center;">
        <ul>
            <li><a href="{% url 'chineseSpicyFlavor:covidWarning' %}">Home Page</a></li>
            <li><a href="#">ACCOUNT</a>
                <ul>

                    <li><a href="{% url 'chineseSpicyFlavor:edit' %}">Edit Account</a></li>

                </ul>
            </li>

            <li><a href="#">ADDRESSES</a>
                <ul>

                    <li><a href="{% url 'chineseSpicyFlavor:address_new' %}">Add an address</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:displayAddresses' %}">My Addresses</a></li>

                </ul>
            </li>

            <li><a href="#">MENU</a>
                <ul>
                    <li><a href="{% url 'chineseSpicyFlavor:product_list' %}">Foods</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:product_list' %}">Order Now</a></li>
                </ul>
            </li>

            <li><a href="#">ORDER</a>
                <ul>
                    <li><a href="{% url 'chineseSpicyFlavor:product_list' %}">Order Now</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:myOrders' %}">My Orders</a></li>

                </ul>
            </li>
            {% if user.is_staff %}
            <li><a href="#">ADMIN</a>
                <ul>
                    <li><a href="{% url 'chineseSpicyFlavor:ViewAllOrders' %}">Orders</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:Sales' %}">Sales</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:Customers' %}">Customers</a></li>
                </ul>
            </li>
            {% endif %}

            <ul>
                <li><a href="{% url 'chineseSpicyFlavor:logout' %}">Logout</a></li>
            </ul>
        </ul>
    </div>
</div>
<h2>OUR FANTASTIC CUSTOMERS</h2>
<table class="styled-table">
    <thead>
    <tr>
        <th>Username</th>
        <th>Date Of Birth</th>
        <th>Profile Picture</th>

    </tr>
    </thead>
    {% for cust in profile_list %}
        <tbody>
        <tr>
            <td>{{ cust.user }}</td>
            <td>{{ cust.date_of_birth }}</td>
            <td>
                <img src="
                        {% if user.profile.image %}{{ user.profile.image.url }}{% else %}{% static "images/logo_home.PNG" %}{% endif %}"
                     alt="panda" width="100" height="100">
            </td>
        </tr>
        </tbody>


    {% endfor %}
</table>
</body>
</html>

chineseSpicyFlavor/templates/manager/Sales.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sales</title>
    <link rel="stylesheet" href="../../static/css/management.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>


</head>
<body>
<div class="top">
    <div style="text-align: center;">
        <ul>
            <li><a href="{% url 'chineseSpicyFlavor:covidWarning' %}">Home Page</a></li>
            <li><a href="#">ACCOUNT</a>
                <ul>

                    <li><a href="{% url 'chineseSpicyFlavor:edit' %}">Edit Account</a></li>

                </ul>
            </li>

            <li><a href="#">ADDRESSES</a>
                <ul>

                    <li><a href="{% url 'chineseSpicyFlavor:address_new' %}">Add an address</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:displayAddresses' %}">My Addresses</a></li>

                </ul>
            </li>

            <li><a href="#">MENU</a>
                <ul>
                    <li><a href="{% url 'chineseSpicyFlavor:product_list' %}">Foods</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:product_list' %}">Order Now</a></li>
                </ul>
            </li>

            <li><a href="#">ORDER</a>
                <ul>
                    <li><a href="{% url 'chineseSpicyFlavor:product_list' %}">Order Now</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:myOrders' %}">My Orders</a></li>

                </ul>
            </li>
            {% if user.is_staff %}
            <li><a href="#">ADMIN</a>
                <ul>
                    <li><a href="{% url 'chineseSpicyFlavor:ViewAllOrders' %}">Orders</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:Sales' %}">Sales</a></li>
                    <li><a href="{% url 'chineseSpicyFlavor:Customers' %}">Customers</a></li>
                </ul>
            </li>
            {% endif %}

            <ul>
                <li><a href="{% url 'chineseSpicyFlavor:logout' %}">Logout</a></li>
            </ul>
        </ul>
    </div>
</div>
<div id="tSales">
    <h1>Today's Sales</h1>
    <table class="styled-table">
    <thead>
    <tr>
        <th>Customer</th>
        <th>Order ID</th>
        <th>Order Date</th>
        <th>Order Delivery</th>
        <th>Total Cost</th>
        <th colspan="3">Actions</th>

    </tr>
    </thead>

    {% for order in order_list %}
        <tbody>
        <tr>
            <td>{{ order.profile.user }}</td>
            <td>{{ order.id }}</td>
            <td>{{ order.created}}</td>
            {% ifnotequal order.address.pk None %}
                <td>{{ order.address.streetNum }}<br>{{ order.address.city }},{{ order.address.state }}<br>{{ order.address.zipcode }}
                </td>

            {% endifnotequal %}
            {% ifequal order.address.pk None %}
                <td>Chinese Spicy Flavor</td>
            {% endifequal %}
            <td>${{ order.get_total_cost }}</td>
            <td><a href="{% url 'chineseSpicyFlavor:AdminOrderDetail' pk=order.pk %}"
                   class="btn btn-primary">Reciept</a>
                {% if order.paid %}
                    <a href="{% url 'chineseSpicyFlavor:ViewAllOrders' %}" class="btn btn-primary"
                       style="background-color:green;">Paid</a>
                {% else %}
                    <a href="{% url 'chineseSpicyFlavor:ViewAllOrders' %}" class="btn btn-primary"
                       style="background-color: red">Not Paid</a>

                {% endif %}

                <a href="{% url 'chineseSpicyFlavor:AdminOrderDelete' pk=order.pk %}"
                   onclick="return confirm('Are you sure you want to delete?')"
                   class="btn btn-danger">Delete</a>
            </td>

        </tr>
        </tbody>


    {% endfor %}
</table>
</div>
<h1>Daily Total</h1>
<h3>${{ totalSales }}</h3>
</body>
</html>